name: Variables demo
run-name:  Testing secret variable

on: [push]

env:
  owner_name: Abhi
  my_repo_var_value: ${{ vars.MY_REPO_VAR }}
  my_secret_var_value: ${{ secrets.MY_SECRET }}

jobs:
  use_env_var:
    runs-on: ubuntu-latest
    steps:
      - run: echo "My secret data -> $my_secret_var_value"
